name: Test

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  bats:
    name: bats
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up bats
        uses: bats-core/bats-action@3.0.1

      - name: Run test suite
        run: bats tests/awsp.bats
